#' Title
#'
#' \itemize{
#'    \item Total sample: 5,000
#'    \item Valid responses: 1,873
#'    \item Effective response rate: 40.2
#' }
#'
#' @details
#'
#' The 2007 Australian Election Study is the eighth in a series of surveys beginning in 1987 that
#' have been timed to coincide with Australian Federal elections. The series also builds on the
#' 1967, 1969 and 1979 Australian Political Attitudes Surveys. The Australian Election Studies aim
#' to provide a long-term perspective on stability and change in the political attitudes and
#' behaviour of the Australian electorate, and investigate the changing social bases of Australian
#' politics as the economy and society modernise and change character. In addition to these
#' long-term goals they examine the political issues prevalent in the election and assess their
#' importance for the election result.
#'
#' The 2007 survey replicates many questions from the previous Australian Election Studies, but also
#' introduces a variety of new questions including a series of questions of Australia's social
#' welfare system. Other sections cover the respondent's interest in the election campaign and
#' politics, their past and present political affiliation, evaluation of parties and candidates,
#' alignment with parties on various election issues, evaluation of the current economic situation,
#' attitudes to a range of election issues including immigration, terrorism, taxation, unemployment,
#' and interest rates, attitudes to issues relating to the environment and defence, and opinions on
#' various social policy issues including abortion, equal opportunities, sex discrimination, and
#' government assistance to Aborigines.
#'
#' Background variables include level of education, employment status, occupation, type of employer,
#' position at workplace, trade union membership, sex, age, own and parents' country of birth,
#' parents' political preferences, religion, marital status, income, and where applicable, the
#' occupation, trade union membership and political preference of the respondent's spouse.
#'
#' \strong{Useful Links}
#' \itemize{
#'    \item \href{http://ada.edu.au/ADAData/codebooks/ADA.CODEBOOK.01120.rtf.zip}{Original codebook}
#'    \item \href{http://ada.edu.au/ADAData/questionnaires/ADA.QUESTIONNAIRE.01120.pdf.zip}{Original questionnaire}
#' }
#'
#' @source \url{http://www.australianelectionstudy.org/voter_studies.html}
#'
#' @section Variables:
#'
#' Note: this documentation has been autogenerated from the dataset labels not the original codebook.
#'
#' \describe{
#'   \item{accid}{Accession number}
#'   \item{retda}{Day of return}
#'   \item{retmo}{Month of return}
#'   \item{retyr}{Year of return}
#'   \item{a1}{A1. Interest in politics}
#'   \item{a2}{A2. Followed election news in the newspapers}
#'   \item{a3p1}{A3. Followed election news on TV}
#'   \item{a3p2}{A3. Followed election news on the radio}
#'   \item{a3p3}{A3. Followed election news on the internet}
#'   \item{a4}{A4. Interest in election campaign}
#'   \item{a5p1}{A5. During election: discussed politics with others}
#'   \item{a5p2}{A5. During election: talk to people about vote}
#'   \item{a5p3}{A5. During election: work for party/candidate}
#'   \item{a5p4}{A5. During election: go to meetings or rallies}
#'   \item{a5p5}{A5. During campaign: contribute money}
#'   \item{a6}{A6. Candidate persuade you to vote for them}
#'   \item{a7}{A7. Watched televised debate 21 October}
#'   \item{a8}{A8. Who performed better in televised debate}
#'   \item{a9}{A9. Use internet to get news on 2007 election}
#'   \item{a10p1}{A10. Website: Party}
#'   \item{a10p2}{A10. Website: Own MP}
#'   \item{a10p3}{A10. Website: Individual candidate in your electorate}
#'   \item{a10p4}{A10. Website: Other candidate/MP outside your electorate}
#'   \item{a10p5}{A10. Website: Federal parliament}
#'   \item{a10p6}{A10. Website: Australian Electoral Commission}
#'   \item{a10p7}{A10. Website: Mainstream news media}
#'   \item{a10p8}{A10. Website: YouTube}
#'   \item{a10p9}{A10. Website: Political weblog/blog}
#'   \item{a11}{A11. Should voting be compulsory}
#'   \item{a12}{A12. Would you vote if voting not compulsory}
#'   \item{a13}{A13. Know how much those not vote are fines}
#'   \item{a14}{A14. Know someone who didn't vote with no good reason}
#'   \item{a15}{A15. How likely person will pay fine - didn't vote}
#'   \item{b1}{B1. Party identification}
#'   \item{xb1}{B1. Extended-Party identification}
#'   \item{b2}{B2. Strength of party identification}
#'   \item{b3}{B3. Care which party wins election}
#'   \item{b4}{B4. When decided which way to vote}
#'   \item{b5}{B5. Most important in vote decision}
#'   \item{b6p1}{B6. Labor's inexperience in government}
#'   \item{b6p2}{B6. Time for a change}
#'   \item{b6p3}{B6. Number of trade union leaders in Labor government}
#'   \item{b6p4}{B6. Howard government's WorkChoices legislation}
#'   \item{b6p5}{B6. Labor governments in Canberra and all states}
#'   \item{b6p6}{B6. Rises in interest rates}
#'   \item{b7}{B7. Prefer when Govt controls both houses}
#'   \item{b8}{B8. Difference between Labor and Liberal}
#'   \item{b9own}{B9. Own left-right position}
#'   \item{b10lib}{B10. Liberal left-right position}
#'   \item{b10alp}{B10. Labor left-right position}
#'   \item{b10nat}{B10. Nationals left-right position}
#'   \item{b10grn}{B10. Greens left-right position}
#'   \item{b11reps}{B11. Vote in House of Representatives}
#'   \item{xb11reps}{B11. Extended-Vote in House of Representatives}
#'   \item{b11senat}{B11. Vote in Senate}
#'   \item{xb11sena}{B11. Extended-Vote in Senate}
#'   \item{b12reps}{B12. Preferences to in House of Reps}
#'   \item{b12senat}{B12. Preferences to in Senate}
#'   \item{b13}{B13. Followed How to Vote card for H of R}
#'   \item{b14}{B14. Party box or own preferences for Senate}
#'   \item{b15}{B15. Thought of changing vote during campaign}
#'   \item{b16p1}{B16. Parties never vote for - No}
#'   \item{b16p2}{B16. Parties never vote for - Yes, Liberal}
#'   \item{b16p3}{B16. Parties never vote for - Yes, Labor}
#'   \item{b16p4}{B16. Parties never vote for - Yes, National}
#'   \item{b16p5}{B16. Parties never vote for - Yes, Greens}
#'   \item{b16p6}{B16. Parties never vote for - Yes, another party/independent}
#'   \item{b17}{B17. Vote in House of Representatives in 2004}
#'   \item{b18p1}{B18. How probable ever vote Liberal}
#'   \item{b18p2}{B18. How probable ever vote Labor}
#'   \item{b18p3}{B18. How probable ever vote National}
#'   \item{b18p4}{B18. How probable ever vote Greens}
#'   \item{b19p1}{B19. Previous vote - always same}
#'   \item{b19p2}{B19. Previous vote - sometimes Liberal}
#'   \item{b19p3}{B19. Previous vote - sometimes Labor}
#'   \item{b19p4}{B19. Previous vote - sometimes National}
#'   \item{b19p5}{B19. Previous vote - sometimes Democrats}
#'   \item{b19p6}{B19. Previous vote - sometimes Greens}
#'   \item{b19p7}{B19. Previous vote - sometimes other party/independent}
#'   \item{b19p8}{B19. Previous vote - not before this election}
#'   \item{b20}{B20. Elections ensure all voters represented}
#'   \item{b21p1}{B21. Party represents your views best - Liberal Party}
#'   \item{b21p2}{B21. Party represents your views best - Labor Party (ALP)}
#'   \item{b21p3}{B21. Party represents your views best - National Party}
#'   \item{b21p4}{B21. Party represents your views best - Greens}
#'   \item{b21p5}{B21. Party represents your views best - Other party}
#'   \item{b21p6}{B21. Party represents your views best - No party represents well}
#'   \item{b22}{B22. Feel closer to one party than others}
#'   \item{b23}{B23. Party leader represents your views best}
#'   \item{b24}{B24. Political parties care what people think}
#'   \item{b25}{B25. Political parties make system work}
#'   \item{b26lib}{B26. Feelings about Liberal Party}
#'   \item{b26alp}{B26. Feelings about Labor Party}
#'   \item{b26nat}{B26. Feelings about National Party}
#'   \item{b26grn}{B26. Feelings about Greens}
#'   \item{c1howard}{C1. Feelings about John Howard}
#'   \item{c1rudd}{C1. Feelings about Kevin Rudd}
#'   \item{c1vaile}{C1. Feelings about Mark Vaile}
#'   \item{c1brown}{C1. Feelings about Bob Brown}
#'   \item{c1costel}{C1. Feelings about Peter Costello}
#'   \item{c1gillar}{C1. Feelings about Julia Gillard}
#'   \item{c2jhint}{C2. John Howard intelligent}
#'   \item{c2jhcmps}{C2. John Howard compassionate}
#'   \item{c2jhcmpt}{C2. John Howard competent}
#'   \item{c2jhsen}{C2. John Howard sensible}
#'   \item{c2jhlea}{C2. John Howard provides strong leadership}
#'   \item{c2jhhon}{C2. John Howard honest}
#'   \item{c2jhkno}{C2. John Howard knowledgeable}
#'   \item{c2jhins}{C2. John Howard inspiring}
#'   \item{c2jhtru}{C2. John Howard trustworthy}
#'   \item{c3krint}{C3. Kevin Rudd intelligent}
#'   \item{c3krcmps}{C3. Kevin Rudd compassionate}
#'   \item{c3krcmpt}{C3. Kevin Rudd competent}
#'   \item{c3krsen}{C3. Kevin Rudd sensible}
#'   \item{c3krlea}{C3. Kevin Rudd provides strong leadership}
#'   \item{c3krhon}{C3. Kevin Rudd honest}
#'   \item{c3krkno}{C3. Kevin Rudd knowledgeable}
#'   \item{c3krins}{C3. Kevin Rudd inspiring}
#'   \item{c3krtru}{C3. Kevin Rudd trustworthy}
#'   \item{c4}{C4. Fed Politicians know what people think}
#'   \item{c5}{C5. Doesn't make a difference who in power}
#'   \item{c6}{C6. Doesn't make a difference who vote for}
#'   \item{c7}{C7. Satisfied with Aust democracy}
#'   \item{c8}{C8. Government looks after themselves}
#'   \item{c9}{C9. Government run by big interests}
#'   \item{c10}{C10. Performance of govt in Canb 3 yrs}
#'   \item{c11p1}{C11. 5 yrs done to express views-contact official}
#'   \item{c11p2}{C11. 5 yrs done to express views-protest/march}
#'   \item{c11p3}{C11. 5 yrs done to express views-work with like others}
#'   \item{c11p4}{C11. 5 yrs done to express views-signed written petition}
#'   \item{c11p5}{C11. 5 yrs done to express views-signed electronic petition}
#'   \item{c12p1}{C12. Strong leader who doesn't bother with parliament}
#'   \item{c12p2}{C12. Experts, not government, make decisions}
#'   \item{c12p3}{C12. Having the army rule}
#'   \item{c12p4}{C12. Having a democratic political system}
#'   \item{d1tax}{D1. Importance of taxation}
#'   \item{d1immig}{D1. Importance of immigration}
#'   \item{d1educ}{D1. Importance of education}
#'   \item{d1envir}{D1. Importance of environment}
#'   \item{d1indrel}{D1. Importance of industrial relations}
#'   \item{d1health}{D1. Importance of health and Medicare}
#'   \item{d1defenc}{D1. Importance of defence, national security}
#'   \item{d1global}{D1. Importance of global warming}
#'   \item{d1water}{D1. Importance of management of water}
#'   \item{d1unemp}{D1. Importance of unemployment}
#'   \item{d1aborig}{D1. Importance of treatment of Aborigines}
#'   \item{d1inter}{D1. Importance of interest rates}
#'   \item{d1iraq}{D1. Importance of the war in Iraq}
#'   \item{d1terror}{D1. Importance of terrorism}
#'   \item{d2tax}{D2. Party closest to own view taxation}
#'   \item{d2immig}{D2. Party closest to own view immigration}
#'   \item{d2educ}{D2. Party closest to own view education}
#'   \item{d2envir}{D2. Party closest to own view environment}
#'   \item{d2indrel}{D2. Party closest to own view industrial relations}
#'   \item{d2health}{D2. Party closest to own view health and Medicare}
#'   \item{d2defenc}{D2. Party closest to own view defence, national security}
#'   \item{d2global}{D2. Party closest to own view global warming}
#'   \item{d2water}{D2. Party closest to own view management of water}
#'   \item{d2unemp}{D2. Party closest to own view unemployment}
#'   \item{d2aborig}{D2. Party closest to own view treatment of Aborigines}
#'   \item{d2inter}{D2. Party closest to own view interest rates}
#'   \item{d2iraq}{D2. Party closest to own view the war in Iraq}
#'   \item{d2terror}{D2. Party closest to own view terrorism}
#'   \item{d3p1}{D3. Most important issue during election campaign}
#'   \item{d3p2}{D3. Second important issue during election campaign}
#'   \item{d4p1}{D4. Most important political problem facing Australia}
#'   \item{d4p2}{D4. Second important political problem facing Australia}
#'   \item{d5p1}{D5. Party best to deal with most important political problem}
#'   \item{d5p2}{D5. Party best to deal with second important political problem}
#'   \item{d6hhold}{D6. Financial situation of hhold now to 1 yr ago}
#'   \item{d6cntry}{D6. Economic situation country now to 1 yr ago}
#'   \item{d7hhold}{D7. Effect of govt policies on hhold situation}
#'   \item{d7cntry}{D7. Effect of govt policies on country situation}
#'   \item{d8hhold}{D8. Financial situation of hhold in 1 yr}
#'   \item{d8cntry}{D8. Economic situation country in 1 yr}
#'   \item{d9hhold}{D9. Effect of govt policies on hhold situation in 1 yr}
#'   \item{d9cntry}{D9. Effect of govt policies on country situation in 1 yr}
#'   \item{d10}{D10. Worry that hhold member will unemployed next 12 months}
#'   \item{d11}{D11. How easy to get a job}
#'   \item{d12}{D12. Job availability better in past or future}
#'   \item{d13}{D13. How worried about increases in interest rates}
#'   \item{d14p1}{D14. Unemployment since 2004 Fed election}
#'   \item{d14p2}{D14. Prices since 2004 Federal election}
#'   \item{d14p3}{D14. Taxes since 2004 Federal election}
#'   \item{d14p4}{D14. Standard of health services since 2004 Fed election}
#'   \item{d14p5}{D14. Quality of education since 2004 Fed election}
#'   \item{d14p6}{D14. Quality of indust rels since 2004 Fed election}
#'   \item{d14p7}{D14. Own standard of living since 2004 Fed election}
#'   \item{d14p8}{D14. General standard of living since 2004 Fed election}
#'   \item{d15p1}{D15. High tax makes peoples less willing to work}
#'   \item{d15p2}{D15. Trade unions have too much power}
#'   \item{d15p3}{D15. Big business has too much power}
#'   \item{d15p4}{D15. Income and wealth should be redistributed}
#'   \item{d15p5}{D15. Private schools offer better education than public}
#'   \item{d15p6}{D15. Stricter laws to regulate trade unions}
#'   \item{d16}{D16. Know about WorkChoices changes}
#'   \item{d17}{D17. Approve WorkChoices changes}
#'   \item{d18}{D18. Australia participate in Kyoto agreement}
#'   \item{d19}{D19. Will global warming pose serious threat to way of life}
#'   \item{d20}{D20. How likely to join any environmental groups}
#'   \item{d21p1}{D21. Environmental proposal higher emission standards for cars}
#'   \item{d21p2}{D21. Environmental proposal build nuclear power stations}
#'   \item{d21p3}{D21. Environmental proposal higher emission standards for business}
#'   \item{d21p4}{D21. Environmental proposal desalination plants}
#'   \item{d21p5}{D21. Environmental proposal developing solar and wind power}
#'   \item{e1}{E1. Choice between taxes and social services}
#'   \item{e2migeo}{E2. Equal opportunities for migrants}
#'   \item{e2nudsex}{E2. Nudity & sex in films and magazines}
#'   \item{e2abland}{E2. Aboriginal land rights}
#'   \item{e2equop}{E2. Equal opportunities for women}
#'   \item{e2immig}{E2. No. of migrants allowed into Australia}
#'   \item{e2abor}{E2. Government help for aborigines}
#'   \item{e2asia}{E2. Building closer links with Asia}
#'   \item{e2arms}{E2. Government controls on firearms}
#'   \item{e2terror}{E2. Aust support fight against terrorism}
#'   \item{e3}{E3. Feelings about abortion}
#'   \item{e4}{E4. Feelings about same sex marriage}
#'   \item{e5deathp}{E5. Death penalty reintroduced for murder}
#'   \item{e5marij}{E5. Decriminalise smoking of marijuana}
#'   \item{e5lawbrk}{E5. Stiffer sentences if break law}
#'   \item{e5pollut}{E5. Stronger measures against pollution}
#'   \item{e5pref}{E5. Women given preferential treatment}
#'   \item{e5opp}{E5. Increase business opportunities for women}
#'   \item{e5nuclea}{E5. Nuclear energy a real necessity}
#'   \item{e5uraniu}{E5. Australia should mine uranium}
#'   \item{e6p1}{E6. Government generous to unemployed people}
#'   \item{e6p2}{E6. Government generous to working couples w children}
#'   \item{e6p3}{E6. Government generous to single parents}
#'   \item{e6p4}{E6. Government generous to retired people no super}
#'   \item{e6p5}{E6. Government generous to aboriginal people unemployed}
#'   \item{e6p6}{E6. Government generous to people investing in super}
#'   \item{e6p7}{E6. Government generous to people receiving disability payments}
#'   \item{e6p8}{E6. Government generous to people caring for sick relative}
#'   \item{e6p9}{E6. Government generous to people taking out private health cover}
#'   \item{e6p10}{E6. Government generous to new immigrants to Australia}
#'   \item{e6p11}{E6. Government generous to people buy first home}
#'   \item{e7p1}{E7. Deserve govt help unemployed people}
#'   \item{e7p2}{E7. Deserve govt help working couples w children}
#'   \item{e7p3}{E7. Deserve govt help single parents}
#'   \item{e7p4}{E7. Deserve govt help retired people no super}
#'   \item{e7p5}{E7. Deserve govt help aboriginal people unemployed}
#'   \item{e7p6}{E7. Deserve govt help people investing in super}
#'   \item{e7p7}{E7. Deserve govt help people receiving disability payments}
#'   \item{e7p8}{E7. Deserve govt help people caring for sick relative}
#'   \item{e7p9}{E7. Deserve govt help people taking out private health cover}
#'   \item{e7p10}{E7. Deserve govt help new immigrants to Australia}
#'   \item{e7p11}{E7. Deserve govt help people buy first home}
#'   \item{e8p1}{E8. Received benefits 5 yrs - Family payments}
#'   \item{e8p2}{E8. Received benefits 5 yrs - Unemployment}
#'   \item{e8p3}{E8. Received benefits 5 yrs - Age pension}
#'   \item{e8p4}{E8. Received benefits 5 yrs - Disability support}
#'   \item{e8p5}{E8. Received benefits 5 yrs - Private health insurance rebate}
#'   \item{e8p6}{E8. Received benefits 5 yrs - Child care benefit}
#'   \item{e8p7}{E8. Received benefits 5 yrs - Baby bonus}
#'   \item{e8p8}{E8. Received benefits 5 yrs - Single parent payment}
#'   \item{e8p9}{E8. Received benefits 5 yrs - Parenting payment}
#'   \item{e8p10}{E8. Received benefits 5 yrs - Youth allowance}
#'   \item{e8p11}{E8. Received benefits 5 yrs - First home owner grant}
#'   \item{e8p12}{E8. Received benefits 5 yrs - Other}
#'   \item{e9p1}{E9. Aims 10yrs 1-First choice}
#'   \item{e9p2}{E9. Aims 10yrs 1-Second choice}
#'   \item{e10p1}{E10. Aims 10yrs 2-First choice}
#'   \item{e10p2}{E10. Aims 10yrs 2-Second choice}
#'   \item{e11p1}{E11. Aims 10yrs 3-First choice}
#'   \item{e11p2}{E11. Aims 10yrs 3-Second choice}
#'   \item{e12p1}{E12. Overwhelmed by precautions for health risks}
#'   \item{e12p2}{E12. Trust medical specialists to make right decisions}
#'   \item{e12p3}{E12. Globalisation increase number of different health risks}
#'   \item{e12p4}{E12. Ordinary people need to keep up with scientific advances}
#'   \item{e12p5}{E12. People more anxious about health risks}
#'   \item{e12p6}{E12. I try to find out as much as possible before medical procedures}
#'   \item{f1}{F1. United States alliance under ANZUS}
#'   \item{f2}{F2. If Australia threatened trust US come to defence}
#'   \item{f3japan}{F3. Japan threat to Aust. security}
#'   \item{f3us}{F3. United States threat to Aust. security}
#'   \item{f3china}{F3. China threat to Aust. security}
#'   \item{f3vietn}{F3. Vietnam threat to Aust. security}
#'   \item{f3malay}{F3. Malaysia threat to Aust. security}
#'   \item{f3indon}{F3. Indonesia threat to Aust. security}
#'   \item{f4}{F4. Government spend more on defence}
#'   \item{f5p1}{F5. Aust defence stronger than 10 yrs ago}
#'   \item{f5p2}{F5. Acts of terror in Aust in the future}
#'   \item{f5p3}{F5. Security agreements between Aust and Indon}
#'   \item{f5p4}{F5. Aust would be able to defend itself}
#'   \item{f5p5}{F5. Freedom of speech not extend to terrorists}
#'   \item{f5p6}{F5. Police search terrorists without court order}
#'   \item{f5p7}{F5. Aust trading future lies with Asia}
#'   \item{f5p8}{F5. Aust provide military for war on terrorism}
#'   \item{f6}{F6. Approve of way Howard handled war in Iraq}
#'   \item{f7}{F7. War in Iraq been worth the cost}
#'   \item{f8}{F8. Threat of terrorism against Australia increased}
#'   \item{f9}{F9. Govt doing all can to prevent terror attacks in Aust}
#'   \item{f10}{F10. How concerned being victim of terror attack}
#'   \item{f11}{F11. How concerned major terror attack near future}
#'   \item{f12}{F12. Number of immigrants increased}
#'   \item{f13p1}{F13. Immigrants increase crime}
#'   \item{f13p2}{F13. Immigrants good for economy}
#'   \item{f13p3}{F13. Immigrants take jobs from Aust}
#'   \item{f13p4}{F13. Immigrants make Aust more open}
#'   \item{f14p1}{F14. Immigrants not citizens can still committed to Aust}
#'   \item{f14p2}{F14. Immigrants don't have to speak English}
#'   \item{f14p3}{F14. Immigrants must speak English when with Australians}
#'   \item{f14p4}{F14. Immigrants here illegally not allowed to stay}
#'   \item{f14p5}{F14. Immigrants can be selective about first job}
#'   \item{f14p6}{F14. Immigrants speak English in own homes}
#'   \item{f14p7}{F14. Immigrants treat women as equals in own home}
#'   \item{f14p8}{F14. Immigrants treat women according to own culture}
#'   \item{f14p9}{F14. Immigrants enter legally just like other Aust}
#'   \item{f14p10}{F14. Immigrants educate selves about culture of new country}
#'   \item{f15}{F15. Most people can be trusted}
#'   \item{f16}{F16. Importance of Queen}
#'   \item{f17}{F17. Australia a republic}
#'   \item{f18}{F18. Head of republic from voters}
#'   \item{f19}{F19. Proud to be Australian}
#'   \item{f20}{F20. Own shares in Australian stock exchange}
#'   \item{f21p1}{F21. Quiz - Australia became federation in 1901}
#'   \item{f21p2}{F21. Quiz - 75 members of House of Reps}
#'   \item{f21p3}{F21. Quiz - Constitution changed by High Court}
#'   \item{f21p4}{F21. Quiz - Elections to Senate proportional}
#'   \item{f21p5}{F21. Quiz - No-one stands unless pay deposit}
#'   \item{f21p6}{F21. Quiz - Longest time between Fed elections 4 years}
#'   \item{g1}{G1. Age left school}
#'   \item{g2}{G2. No. years tertiary education}
#'   \item{g3}{G3. Highest qualification since leaving school}
#'   \item{g4}{G4. Occupation last week}
#'   \item{g5you}{G5. Secondary school attended - You}
#'   \item{g5child}{G5. Secondary school attended - Child}
#'   \item{g6}{G6. Occupation (ANZSCO 2 digit)}
#'   \item{xg6}{G6. Extended-Occupation (ANZSCO 2 digit)}
#'   \item{g6pos}{G6. Position in organisation}
#'   \item{g6employ}{G6. Employer}
#'   \item{g6superv}{G6. Supervisory responsibility}
#'   \item{g7}{G7. Belong to a trade union}
#'   \item{h1}{H1. Sex}
#'   \item{h2}{H2. Year of birth}
#'   \item{h3own}{H3. Country of birth}
#'   \item{xh3own}{H3. Extended-Country of birth}
#'   \item{h3mum}{H3. Mothers country of birth}
#'   \item{xh3mum}{H3. Extended-Mothers country of birth}
#'   \item{h3dad}{H3. Fathers country of birth}
#'   \item{xh3dad}{H3. Extended-Fathers country of birth}
#'   \item{h4}{H4. Year came to Australia}
#'   \item{h5dad}{H5. Fathers party ID at 14}
#'   \item{h5mum}{H5. Mothers party ID at 14}
#'   \item{h6}{H6. Religion}
#'   \item{xh6}{H6. Extended-Religion}
#'   \item{h7}{H7. Religious attendance}
#'   \item{h8}{H8. Marital status}
#'   \item{h9}{H9. Own, buying or rent home}
#'   \item{h10}{H10. How often use internet}
#'   \item{h11}{H11. When start using internet}
#'   \item{h12p1}{H12. Use internet to become more involved with groups}
#'   \item{h12p2}{H12. Use internet to interact share hobbies}
#'   \item{h12p3}{H12. Use internet to interact share religion}
#'   \item{h12p4}{H12. Use internet to interact share political beliefs}
#'   \item{h12p5}{H12. Use internet to interact ethnic backgrounds}
#'   \item{h12p6}{H12. Use internet to interact different ages}
#'   \item{h12p7}{H12. Use internet to interact other countries}
#'   \item{h12p8}{H12. Use internet to interact family and friends}
#'   \item{h13}{H13. Last month how often communication with friends email/internet}
#'   \item{h14}{H14. Social class}
#'   \item{h15}{H15. Live rural or urban}
#'   \item{h16}{H16. Gross annual income}
#'   \item{h17}{H17. Spouse working now}
#'   \item{h18}{H18. Spouse Occupation (ANZSCO 2 digit)}
#'   \item{xh18}{H18. Extended-Spouse Occupation (ANZSCO 2 digit)}
#'   \item{h19}{H19. Spouse employer}
#'   \item{h20}{H20. Does spouse supervise people at work}
#'   \item{h21}{H21. Spouse member of trade union}
#'   \item{h22}{H22. Spouse party identification}
#'   \item{xh22}{H22. Extended-Spouse party identification}
#'   \item{state}{State}
#'   \item{elecdiv}{Electoral Division}
#'   \item{pcode}{RESTRICTED VARIABLE: Postcode}
#'   \item{region}{Region}
#'   \item{statemap}{State mapping variable}
#' }
"aes_2007"
