#' Australian Election Study 1993
#'
#' \itemize{
#'    \item Total sample: 4,950
#'    \item Valid responses: 3,023
#'    \item Effective response rate: 62.8
#' }
#'
#' @details
#'
#' The 1993 Australian Election Study is the third in a series of surveys beginning in 1987 which have been timed to coincide with Australian Federal elections. The series also builds on the 1967, 1969 and 1979 Australian Political Attitudes Surveys. The Australian Election Studies aim to provide a long-term perspective on stability and change in the political attitudes and behaviour of the Australian electorate, and investigate the changing social bases of Australian politics as the economy and society modernise and change character. In addition to these long-term goals they examine the political issues prevalent in the election and assess their importance for the election result.
#'
#' The 1993 survey replicates many questions from the 1987 and 1990 Australian Election Studies, but also introduces a variety of new questions including a section on foreign affairs and defence, and attitudes to Federal and State government. As in previous surveys, other sections covered the respondent's interest in the election campaign and politics, their past and present political affiliation, evaluation of parties and candidates, alignment with parties on various election issues, evaluation of the economic situation and economic policies, attitudes to a range of environmental issues, and attitudes to contemporary social policy issues including equal opportunity, censorship, migration, assistance for aborigines, abortion, criminal law, expenditure on social services, the monarchy and the Australian flag.
#'
#' Background variables covered include level of education, employment status, occupation, type of employer, position at workplace, trade union membership, sex, year and place of birth, parents' birthplaces, parents' political preferences, father's occupation, length of residence in state or territory, religion, marital status, number of children, income, and where applicable, the occupation, trade union membership and political preference of the respondent's spouse.
#'
#' \strong{Useful Links}
#' \itemize{
#'    \item \href{http://ada.edu.au/ADAData/codebooks/ADA.CODEBOOK.00763.rtf.zip}{Original codebook}
#'    \item \href{http://ada.edu.au/ADAData/questionnaires/ADA.QUESTIONNAIRE.00763.pdf.zip}{Original questionnaire}
#' }
#'
#' @source \url{http://www.australianelectionstudy.org/voter_studies.html}
#'
#' @section Variables:
#'
#' Note: this documentation has been autogenerated from the dataset labels not the original codebook.
#'
#' \describe{
#'   \item{id}{Case identification number}
#'   \item{a1}{Followed election news in the newspapers}
#'   \item{a2p1}{Followed election news on TV}
#'   \item{a2p2}{Followed election news on the radio}
#'   \item{a3}{Interest in politics}
#'   \item{a4}{Interest in election campaign}
#'   \item{a5}{Watched televised debate}
#'   \item{a6}{Who performed better in televised debate}
#'   \item{a7}{Which was more important in deciding}
#'   \item{a8p1}{Discussed politics with others}
#'   \item{a8p2}{Talk to people about vote}
#'   \item{a8p3}{Go to meetings or rallies}
#'   \item{a8p4}{Contribute money}
#'   \item{a8p5}{Work for party or candidate}
#'   \item{a9}{Care which party wins election}
#'   \item{a10}{Better with majority in both houses}
#'   \item{a11}{Compulsory voting}
#'   \item{b1}{Party identification}
#'   \item{b2}{Strength of party identification}
#'   \item{b3}{Left-right position}
#'   \item{b4}{When decided which way to vote}
#'   \item{b5}{Which party would win election}
#'   \item{b6reps}{Vote in House of Representatives}
#'   \item{b6senate}{Vote in Senate}
#'   \item{b7}{Reason chose party for House of Reps}
#'   \item{b8}{Thought of changing vote during campaign}
#'   \item{b9reps}{Vote in House of Representatives in 1990}
#'   \item{b9senate}{Vote in Senate in 1990}
#'   \item{b10p1}{Previous vote - always same}
#'   \item{b10p2}{Previous vote - sometimes Liberal}
#'   \item{b10p3}{Previous vote - sometimes Labor}
#'   \item{b10p4}{Previous vote - sometimes National}
#'   \item{b10p5}{Previous vote - sometimes Democrat}
#'   \item{b10p6}{Previous vote - sometimes others}
#'   \item{b10p7}{Previous vote - not before this election}
#'   \item{b11}{Difference between parties}
#'   \item{b12lib}{Feelings about Liberal Party}
#'   \item{b12alp}{Feelings about Labor Party}
#'   \item{b12nat}{Feelings about National Party}
#'   \item{b12demo}{Feelings about Australian Democrats}
#'   \item{b12green}{Feelings about Greens}
#'   \item{c1pk}{Feelings about Paul Keating}
#'   \item{c1jhew}{Feelings about John Hewson}
#'   \item{c1tf}{Feelings about Tim Fischer}
#'   \item{c1jcou}{Feelings about John Coulter}
#'   \item{c2}{Like about Paul Keating}
#'   \item{c3}{Like about John Hewson}
#'   \item{c4pkmor}{Paul Keating moral}
#'   \item{c4pkint}{Paul Keating intelligent}
#'   \item{c4pkcom}{Paul Keating compassionate}
#'   \item{c4pksen}{Paul Keating sensible}
#'   \item{c4pklea}{Paul Keating provides strong leadership}
#'   \item{c4pkdec}{Paul Keating decent}
#'   \item{c4pkrel}{Paul Keating reliable}
#'   \item{c4pkkno}{Paul Keating knowledgeable}
#'   \item{c4pkins}{Paul Keating inspiring}
#'   \item{c4pkdep}{Paul Keating dependable}
#'   \item{c4jhmor}{John Hewson moral}
#'   \item{c4jhint}{John Hewson intelligent}
#'   \item{c4jhcom}{John Hewson compassionate}
#'   \item{c4jhsen}{John Hewson sensible}
#'   \item{c4jhlea}{John Hewson provides strong leadership}
#'   \item{c4jhdec}{John Hewson decent}
#'   \item{c4jhrel}{John Hewson reliable}
#'   \item{c4jhkno}{John Hewson knowledgeable}
#'   \item{c4jhins}{John Hewson inspiring}
#'   \item{c4jhdep}{John Hewson dependable}
#'   \item{c5name}{Name of local Federal MP}
#'   \item{c5party}{Party of local Federal MP}
#'   \item{c6pers}{Meeting the MP personally}
#'   \item{c6spok}{Attending a meeting where the MP spoke}
#'   \item{c6mail}{Receiving something in the mail}
#'   \item{c6read}{Reading in newspaper or magazine}
#'   \item{c6radio}{Hearing the MP on radio}
#'   \item{c6tv}{Seeing the MP on TV}
#'   \item{c6none}{No contact}
#'   \item{c7}{Contacted Federal MP in office}
#'   \item{c7expr}{Contacted to express opinion}
#'   \item{c7info}{Contacted to seek information}
#'   \item{c7help}{Contacted to seek help}
#'   \item{c7satis}{Satisfaction with response}
#'   \item{c8}{Approve of local Federal MP}
#'   \item{d1bus}{Party closest to own view business tax}
#'   \item{d1child}{Part closest to own view child care}
#'   \item{d1educ}{Party closest to own view education}
#'   \item{d1envir}{Party closest to own view environment}
#'   \item{d1enter}{Party closest to own view bargaining}
#'   \item{d1gst}{Party closest to own view on GST}
#'   \item{d1health}{Part closest to own view on health}
#'   \item{d1contr}{Party closest to own view on contracts}
#'   \item{d1inflat}{Party closest to own view on inflation}
#'   \item{d1intr}{Party closest to own view interest rates}
#'   \item{d1medic}{Party closest to own view on Medicare}
#'   \item{d1ss}{Party closest to own view SS benefits}
#'   \item{d1tariff}{Party closest to own view tariffs}
#'   \item{d1unem}{Party closest to own view unemployment}
#'   \item{d2bus}{Importance of business taxes}
#'   \item{d2child}{Importance of child care}
#'   \item{d2educ}{Importance of education}
#'   \item{d2envir}{Importance of the environment}
#'   \item{d2enter}{Importance of enterprise bargaining}
#'   \item{d2gst}{Importance of GST}
#'   \item{d2health}{Importance of health}
#'   \item{d2contr}{Importance of individual contracts}
#'   \item{d2inflat}{Importance of inflation}
#'   \item{d2intr}{Importance of interest rates}
#'   \item{d2medic}{Importance of Medicare}
#'   \item{d2ss}{Importance of SS benefits}
#'   \item{d2tariff}{Importance of tariffs}
#'   \item{d2unem}{Importance of unemployment}
#'   \item{d3a1}{Issue of most concern last 12 months}
#'   \item{d3a2}{Second issue of concern last 12 months}
#'   \item{d3b1}{Issue of most concern in 10 years}
#'   \item{d3b2}{Second issue of concern in 10 years}
#'   \item{d4econ}{Party best for economy}
#'   \item{d4law}{Party best for law and order}
#'   \item{d4for}{Party best for foreign affairs}
#'   \item{d4soc}{Party best for social services}
#'   \item{d4ind}{Party best for industrial relations}
#'   \item{d4int}{Party best for international trade}
#'   \item{d5hhold}{Financial situation of hhold cf 1 yr ago}
#'   \item{d5cntry}{Economic situation country cf 1 yr ago}
#'   \item{d6hhold}{Effect of govt policies on hhold situation}
#'   \item{d6cntry}{Effect of govt policies on country situation}
#'   \item{d7}{Economic situation of country cf 1 yr ahead}
#'   \item{d8}{Effect of govt policies on country situation}
#'   \item{dtax}{High tax makes people less willing to work}
#'   \item{d9redpov}{Spend to reduce poverty}
#'   \item{d9strict}{Stricter laws to regulate trade unions}
#'   \item{d9tupow}{Trade unions have too much power}
#'   \item{d9bigpow}{Big business has too much power}
#'   \item{d9equal}{Income & wealth should be redistributed}
#'   \item{d10}{Employee control of industry}
#'   \item{d11}{Sympathy for or against strikers}
#'   \item{e1}{Choice between taxes and social services}
#'   \item{e2migeo}{Equal opportunities for migrants}
#'   \item{e2nudsex}{Nudity & sex in films & magazines}
#'   \item{e2equop}{Equal opportunities for women}
#'   \item{e2immig}{No. of migrants allowed into Australia}
#'   \item{e2abor}{Government help for aborigines}
#'   \item{e3}{Abortion}
#'   \item{e4}{Censorship of books and films}
#'   \item{e5}{Job opportunities for women}
#'   \item{e6deathp}{Death penalty reintroduced for murder}
#'   \item{e6marij}{Decriminalise smoking of marijuana}
#'   \item{e6ration}{Policies based on rational calculation}
#'   \item{e6lawbrk}{Stiffer sentences if break law}
#'   \item{e6pref}{Women given preferential treatment}
#'   \item{e6succes}{In Australian society anyone can succeed}
#'   \item{e6opp}{Increase opportunities for women}
#'   \item{e6moral}{Policies should be based on morals}
#'   \item{e7}{Royalty}
#'   \item{e8}{Australia should become a republic}
#'   \item{e9}{Change Australia's flag}
#'   \item{e10aims1}{Aims of Australia - first choice}
#'   \item{e10aims2}{Aims of Australia - second choice}
#'   \item{f1nengy}{Nuclear energy a necessity}
#'   \item{f1presn}{Nature most precious in life}
#'   \item{f1uran}{Australian should mine its uranium}
#'   \item{f1spend}{Increase spending to protect environment}
#'   \item{f1bias}{TV is biased in favour of greens}
#'   \item{f1pollut}{Stronger measures against pollution}
#'   \item{f2pollut}{Pollution urgent envir. concern}
#'   \item{f2pop}{Overpopulation urgent envir. concern}
#'   \item{f2waste}{Waste disposal urgent envir. concern}
#'   \item{f2uran}{Uranium mining urgent envir. concern}
#'   \item{f2log}{Logging urgent envir. concern}
#'   \item{f2wild}{Wildlife urgent envir. concern}
#'   \item{f2soil}{Soil urgent envir. concern}
#'   \item{f2ghouse}{Greenhouse urgent envir. concern}
#'   \item{f2urg1}{Most urgent envir. concern}
#'   \item{f2urg2}{Second most urgent envir. concern}
#'   \item{f3envir}{Approve environmental groups}
#'   \item{f3uran}{Approve anti-uranium mining groups}
#'   \item{f3war}{Approve anti-war and anti-nuclear groups}
#'   \item{f4}{Member of environment group}
#'   \item{f5}{Worried about environment cf 5 years ago}
#'   \item{f6}{Views on prices and the environment}
#'   \item{f7}{Views on taxes and the environment}
#'   \item{g1asia}{Trading future lies in Asia}
#'   \item{g1nz}{Increase economic ties with NZ}
#'   \item{g1indo}{Trade agreements with Indonesia}
#'   \item{g1tariff}{Should continue to use tariffs}
#'   \item{g1notus}{Side with Japan not US}
#'   \item{g1japinf}{Japanese influence too great}
#'   \item{g2ausris}{If Australians are at risk}
#'   \item{g2othris}{If others are at risk}
#'   \item{g2oppres}{If country oppresses its own citizens}
#'   \item{g2trade}{If trade is threatened}
#'   \item{g2reques}{If country requests intervention}
#'   \item{g2order}{If country cannot maintain order}
#'   \item{g3}{Spend more or less on defence}
#'   \item{g4russia}{Russia threat to Australia in 5 yrs}
#'   \item{g4china}{China threat to Australia in 5 yrs}
#'   \item{g4indon}{Indonesia threat to Australia in 5 yrs}
#'   \item{g4japan}{Japan threat to Australia in 5 yrs}
#'   \item{g4viet}{Vietnam threat to Australia in 5 yrs}
#'   \item{g4india}{India threat to Australia in 5 yrs}
#'   \item{g5russia}{Russia threat to Australia in 10 yrs}
#'   \item{g5china}{China threat to Australian in 10 yrs}
#'   \item{g5indon}{Indonesia threat to Australia in 10 yrs}
#'   \item{g5japan}{Japan threat to Australia in 10 yrs}
#'   \item{g5viet}{Vietnam threat to Australia in 10 yrs}
#'   \item{g5india}{India threat to Australia in 10 yrs}
#'   \item{g6}{Trust in the United States}
#'   \item{g7}{United States alliance under ANZUS}
#'   \item{g8}{Benefits from Australia's alliance with US}
#'   \item{g9}{Australia-US joint defence facilities}
#'   \item{g10}{Security arrangements}
#'   \item{g11power}{Visits by nuclear powered warships}
#'   \item{g1armed}{Visits by warships with nuclear arms}
#'   \item{h1p1}{Could do good job in public office}
#'   \item{h1p2}{Politics & govt seem so complicated}
#'   \item{h1p3}{Good understanding of political issues}
#'   \item{h1p4}{Public officials don't care much}
#'   \item{h1p5}{Small parties & independent candidates}
#'   \item{h1p6}{Joining a political party}
#'   \item{h1p7}{Well-qualified to participate in politics}
#'   \item{h1p8}{No say about what government does}
#'   \item{h1p9}{Better informed about govt than most}
#'   \item{h2write}{Write to a newspaper}
#'   \item{h2legal}{Go on a legal protest march}
#'   \item{h2banned}{Go on an illegal protest march}
#'   \item{h2meet}{Attend a public meeting}
#'   \item{h2block}{Try to block traffic}
#'   \item{h2petit}{Collect signatures for a petition}
#'   \item{h2disrup}{Disrupt a march or meeting}
#'   \item{h3}{Govt can be trusted to do right}
#'   \item{h4}{Cared about state election result}
#'   \item{h5}{Vote in last state election}
#'   \item{h6p1}{State govts would do better}
#'   \item{h6p2}{Federal govt in touch with state opinion}
#'   \item{h6p3}{Federal govt interferes too much}
#'   \item{h6p4}{Senate keeps check on Federal govt}
#'   \item{h7fed}{Federal government waste money}
#'   \item{h7state}{State government waste money}
#'   \item{h8fed}{Trust in Federal Government}
#'   \item{h8state}{Trust in State Government}
#'   \item{h9fed}{Federal Government run for benefit of}
#'   \item{h9state}{State Government run for benefit of}
#'   \item{h10fed}{Federal Government corrupt}
#'   \item{h10state}{State Government corrupt}
#'   \item{h11}{Which government is more important}
#'   \item{h12}{Which govt more tied up in red tape}
#'   \item{i1}{Age left school}
#'   \item{i2}{Private or non-private school education}
#'   \item{i3}{Highest qual obtained since leaving school}
#'   \item{i4}{No. years of tertiary education}
#'   \item{i5}{Occupation in past week}
#'   \item{i6occup}{Occupation}
#'   \item{i6d}{Employer}
#'   \item{i6e}{No. of employees}
#'   \item{i6f}{Number employed in workplace}
#'   \item{i6g}{Position in organisation}
#'   \item{i7p1}{Supervisory responsibility}
#'   \item{i7p2}{Number supervised}
#'   \item{j1}{Sex}
#'   \item{j2}{Year of birth}
#'   \item{j3own}{Country of birth}
#'   \item{j3mum}{Mothers country of birth}
#'   \item{j3dad}{Fathers country of birth}
#'   \item{j4}{Year R came to Australia}
#'   \item{j5dad}{Fathers political preference at R age 14}
#'   \item{j5mum}{Mothers political preference at R age 14}
#'   \item{j6}{Fathers occupation at R age 14}
#'   \item{j7}{Length of residence}
#'   \item{j8}{Religion}
#'   \item{j9}{Religious attendance}
#'   \item{j10}{Belong to a trade union or staff association}
#'   \item{j11}{Self assessed social class}
#'   \item{j12}{Marital status}
#'   \item{j13a}{Have any children}
#'   \item{j13b1}{No. children under primary school age}
#'   \item{j13b2}{No. children attending primary school}
#'   \item{j13b3}{No. children attending secondary school}
#'   \item{j13b4}{No. children attend university fulltime}
#'   \item{j14}{Income}
#'   \item{j15}{Occupation of spouse}
#'   \item{j16}{Occupation of spouse}
#'   \item{j17}{Employer of spouse}
#'   \item{j18}{Does spouse supervise people at work}
#'   \item{j19}{Spouse member of trade union}
#'   \item{j20}{Spouses political identification}
#'   \item{postcode}{Postcode of Residence}
#'   \item{elecdiv}{Electoral Division}
#'   \item{state}{State of Residence}
#'   \item{region}{Region of electoral division}
#'   \item{weight}{}
#'   \item{c2p1}{Like about Keating 1}
#'   \item{c2p2}{Like about Keating 2}
#'   \item{c2p3}{Like about Keating 3}
#'   \item{c2p4}{Like about Keating 4}
#'   \item{c2p5}{Like about Keating 5}
#'   \item{c2p6}{Like about Keating 6}
#'   \item{c3p1}{Like about Hewson 1}
#'   \item{c3p2}{Like about Hewson 2}
#'   \item{c3p3}{Like about Hewson 3}
#'   \item{c3p4}{Like about Hewson 4}
#'   \item{statemap}{State mapping variable}
#' }
"aes_1993"
