#' Australian Election Study 1998
#'
#' \itemize{
#'    \item Total sample: 3,502
#'    \item Valid responses: 1,896
#'    \item Effective response rate: 57.7
#' }
#'
#' @details
#'
#' The 1998 Australian Election Study is the fifth in a series of surveys beginning in 1987 that
#' have been timed to coincide with Australian Federal elections. The series also builds on the
#' 1967, 1969 and 1979 Australian Political Attitudes Surveys. The Australian Election Studies aim
#' to provide a long-term perspective on stability and change in the political attitudes and
#' behaviour of the Australian electorate, and investigate the changing social bases of Australian
#' politics as the economy and society modernise and change character. In addition to these
#' long-term goals they examine the political issues prevalent in the election and assess their
#' importance for the election result.
#'
#' The 1998 survey replicates many questions from the 1987, 1990, 1993 and 1996 Australian Election
#' Studies, but also introduces a variety of new questions including a section on the constitution,
#' rights and minorities. Other sections cover the respondent's interest in the election campaign
#' and politics, their past and present political affiliation, evaluation of parties and candidates,
#' alignment with parties on various election issues, evaluation of the current economic situation,
#' attitudes to a range of election issues including the GST, immigration, unemployment, the Telstra
#' sale, and education, views on the monarchy and the importance of Australia becoming a republic,
#' attitudes to issues relating to the environment and defence, assessment of the current level of
#' racial prejudice operating in Australia today, and opinions on various social policy issues
#' including euthanasia, abortion, equal opportunities, sex discrimination, and government
#' assistance to Aborigines.
#'
#' Background variables include level of education, employment status, occupation, type of employer,
#' position at workplace, trade union membership, sex, age, own and parents country of birth,
#' parents' political preferences, religion, marital status, income, and where applicable, the
#' occupation, trade union membership and political preference of the respondent's spouse.
#'
#' \strong{Useful Links}
#' \itemize{
#'    \item \href{http://ada.edu.au/ADAData/codebooks/ADA.CODEBOOK.01001.pdf.zip}{Original codebook}
#'    \item \href{http://ada.edu.au/ADAData/questionnaires/ADA.QUESTIONNAIRE.01001.pdf.zip}{Original questionnaire}
#' }
#'
#' @source \url{http://www.australianelectionstudy.org/voter_studies.html}
#'
#' @section Variables:
#'
#' Note: this documentation has been autogenerated from the dataset labels not the original codebook.
#'
#' \describe{
#'   \item{id}{ID Number}
#'   \item{a1}{Interest in politics}
#'   \item{a2}{Followed election news in the newspapers}
#'   \item{a3tel}{Followed election news on TV}
#'   \item{a3radio}{Followed election news on the radio}
#'   \item{a4}{Interest in election campaign}
#'   \item{a5}{Watched televised debates}
#'   \item{a6}{Who performed better in televised debates}
#'   \item{a7p1}{During campaign: discussed politics with others}
#'   \item{a7p2}{During campaign: talk to people about vote}
#'   \item{a7p3}{During campaign: go to meetings or rallies}
#'   \item{a7p4}{During campaign: contribute money}
#'   \item{a7p5}{During campaign: work for party/candidate}
#'   \item{a8}{Should be compulsory voting}
#'   \item{a9}{Would vote if not compulsory voting}
#'   \item{a10p1}{Channel 7 Local News for election news}
#'   \item{a10p2}{Channel 7 National News for election news}
#'   \item{a10p3}{Channel 9 Local News for election news}
#'   \item{a10p4}{Channel 9 National News for election news}
#'   \item{a10p5}{Channel 10 Local News for election news}
#'   \item{a10p6}{Channel 10 National News for election news}
#'   \item{a10p7}{ABC Local News for election news}
#'   \item{a10p8}{ABC National News for election news}
#'   \item{a10p9}{SBS Early World News for election news}
#'   \item{a10p10}{SBS Late World News for election news}
#'   \item{a10p11}{Regional Early News for election news}
#'   \item{a10p12}{Regional Late News for election news}
#'   \item{a11libp1}{Telephoned by the Liberal Party}
#'   \item{a11libp2}{Personally visited by the Liberal Party}
#'   \item{a11libp3}{Sent letter by the Liberal Party}
#'   \item{a11libp4}{Given/Sent pamphlet by the Liberal Party}
#'   \item{a11alpp1}{Telephoned by the Labor Party}
#'   \item{a11alpp2}{Personally visited by the Labor Party}
#'   \item{a11alpp3}{Sent letter by the Labor Party}
#'   \item{a11alpp4}{Given/Sent pamphlet by the Labor Party}
#'   \item{a11natp1}{Telephoned by the National Party}
#'   \item{a11natp2}{Personally visited by the National Party}
#'   \item{a11natp3}{Sent letter by the National Party}
#'   \item{a11natp4}{Given/Sent pamphlet by the National Party}
#'   \item{a11onpp1}{Telephoned by the One Nation Party}
#'   \item{a11onpp2}{Personally visited by One Nation Party}
#'   \item{a11onpp3}{Sent letter by the One Nation Party}
#'   \item{a11onpp4}{Given/Sent pamphlet by One Nation Party}
#'   \item{a11demp1}{Telephoned by the Democrats}
#'   \item{a11demp2}{Personally visited by the Democrats}
#'   \item{a11demp3}{Sent letter by the Democrats}
#'   \item{a11demp4}{Given/Sent pamphlet by the Democrats}
#'   \item{a11grnp1}{Telephoned by the Green Party}
#'   \item{a11grnp2}{Personally visited by the Green Party}
#'   \item{a11grnp3}{Sent letter by the Green Party}
#'   \item{a11grnp4}{Given/Sent pamphlet by the Green Party}
#'   \item{a11othp1}{Telephoned by Other Party}
#'   \item{a11othp2}{Personally visited by Other Party}
#'   \item{a11othp3}{Sent letter by Other Party}
#'   \item{a11othp4}{Given/Sent pamphlet by Other Party}
#'   \item{a12}{Used Internet to get election information}
#'   \item{b1}{Party identification}
#'   \item{b2}{Strength of party identification}
#'   \item{b3}{Care which party wins election}
#'   \item{b4}{When decided which way to vote}
#'   \item{b5}{Most important in vote decision}
#'   \item{b6}{Prefer when Govt controls or doesn't control Senate}
#'   \item{b7}{Difference between Labor and Liberal}
#'   \item{b8}{Parties doing good or bad job}
#'   \item{b9}{Satisfied with Aust democracy}
#'   \item{b10own}{Own left-right position}
#'   \item{b10lib}{Liberal left-right position}
#'   \item{b10alp}{Labor left-right position}
#'   \item{b10nat}{Nationals left-right position}
#'   \item{b10dem}{Democrats left-right position}
#'   \item{b10onp}{One Nation Party left-right position}
#'   \item{b10grn}{Greens left-right position}
#'   \item{b11reps}{Vote in House of Representatives}
#'   \item{b11senat}{Vote in Senate}
#'   \item{b12reps}{Preferences to in House of Reps}
#'   \item{b12senat}{Preferences to in Senate}
#'   \item{b13}{Followed How to Vote card for H of R}
#'   \item{b14}{Party box or own prefs for Senate}
#'   \item{b15}{Thought of changing vote during campaign}
#'   \item{b16}{Vote in House of Representatives in 1996}
#'   \item{b17p1}{Previous vote - always same}
#'   \item{b17p2}{Previous vote - sometimes Liberal}
#'   \item{b17p3}{Previous vote - sometimes Labor}
#'   \item{b17p4}{Previous vote - sometimes National}
#'   \item{b17p5}{Previous vote - sometimes Democrats}
#'   \item{b17p6}{Previous vote - sometimes others}
#'   \item{b17p7}{Previous vote - not before this election}
#'   \item{b18}{Previous State election vote}
#'   \item{b19p1}{Political parties care what people think}
#'   \item{b19p2}{Political parties make system work}
#'   \item{b20lib}{Feelings about Liberal Party}
#'   \item{b20alp}{Feelings about Labor Party}
#'   \item{b20nat}{Feelings about National Party}
#'   \item{b20grn}{Feelings about Greens}
#'   \item{b20onp}{Feelings about One Nation Party}
#'   \item{b20dem}{Feelings about Australian Democrats}
#'   \item{c1beaz}{Feelings about Kim Beazley}
#'   \item{c1how}{Feelings about John Howard}
#'   \item{c1fisch}{Feelings about Tim Fischer}
#'   \item{c1lees}{Feelings about Meg Lees}
#'   \item{c1hans}{Feelings about Pauline Hanson}
#'   \item{c1evans}{Feelings about Gareth Evans}
#'   \item{c1cost}{Feelings about Peter Costello}
#'   \item{c1kern}{Feelings about Cheryl Kernot}
#'   \item{c2jhmor}{John Howard moral}
#'   \item{c2jhint}{John Howard intelligent}
#'   \item{c2jhcom}{John Howard compassionate}
#'   \item{c2jhsen}{John Howard sensible}
#'   \item{c2jhlea}{John Howard provides strong leadership}
#'   \item{c2jhhon}{John Howard honest}
#'   \item{c2jhrel}{John Howard reliable}
#'   \item{c2jhkno}{John Howard knowledgeable}
#'   \item{c2jhins}{John Howard inspiring}
#'   \item{c2jhdep}{John Howard dependable}
#'   \item{c3kbmor}{Kim Beazley moral}
#'   \item{c3kbint}{Kim Beazley intelligent}
#'   \item{c3kbcom}{Kim Beazley compassionate}
#'   \item{c3kbsen}{Kim Beazley sensible}
#'   \item{c3kblea}{Kim Beazley provides strong leadership}
#'   \item{c3kbhon}{Kim Beazley honest}
#'   \item{c3kbrel}{Kim Beazley reliable}
#'   \item{c3kbkno}{Kim Beazley knowledgeable}
#'   \item{c3kbins}{Kim Beazley inspiring}
#'   \item{c3kbdep}{Kim Beazley dependable}
#'   \item{c4phmor}{Pauline Hanson moral}
#'   \item{c4phint}{Pauline Hanson intelligent}
#'   \item{c4phcom}{Pauline Hanson compassionate}
#'   \item{c4phsen}{Pauline Hanson sensible}
#'   \item{c4phlea}{Pauline Hanson provides strong leadership}
#'   \item{c4phhon}{Pauline Hanson honest}
#'   \item{c4phrel}{Pauline Hanson reliable}
#'   \item{c4phkno}{Pauline Hanson knowledgeable}
#'   \item{c4phins}{Pauline Hanson inspiring}
#'   \item{c4phdep}{Pauline Hanson dependable}
#'   \item{c5}{Government looks after themselves}
#'   \item{c6p1}{Fed Politicians know what people think}
#'   \item{c6p2}{Doesn't make a difference who vote for}
#'   \item{d1tax}{Importance of taxation}
#'   \item{d1immig}{Importance of immigration}
#'   \item{d1educ}{Importance of education}
#'   \item{d1envir}{Importance of environment}
#'   \item{d1gst}{Importance of GST}
#'   \item{d1indrel}{Importance of industrial relations}
#'   \item{d1health}{Importance of health and Medicare}
#'   \item{d1asia}{Importance of links with Asia}
#'   \item{d1intrat}{Importance of interest rates}
#'   \item{d1unemp}{Importance of unemployment}
#'   \item{d1priv}{Importance of privatisation}
#'   \item{d1inflat}{Importance of inflation}
#'   \item{d1tlstr}{Importance of Telstra sale}
#'   \item{d2tax}{Party closest to own view taxation}
#'   \item{d2immig}{Party closest to own view immigration}
#'   \item{d2educ}{Party closest to own view education}
#'   \item{d2envir}{Party closest to own view environment}
#'   \item{d2gst}{Party closest to own view GST}
#'   \item{d2indrel}{Party closest to own view industrial relations}
#'   \item{d2health}{Party closest to own view health and Medicare}
#'   \item{d2asia}{Party closest to own view links with Asia}
#'   \item{d2intrat}{Party closest to own view interest rates}
#'   \item{d2unemp}{Party closest to own view unemployment}
#'   \item{d2priv}{Party closest to own view privatisation}
#'   \item{d2inflat}{Party closest to own view inflation}
#'   \item{d2tlstr}{Party closest to own view Telstra sale}
#'   \item{d3p1}{Issue of most concern during election campaign}
#'   \item{d3p2}{Second issue of concern during election campaign}
#'   \item{d4hhold}{Financial situation of hhold now to 1 yr ago}
#'   \item{d4cntry}{Economic situation country now to 1 yr ago}
#'   \item{d5hhold}{Effect of govt policies on hhold situation}
#'   \item{d5cntry}{Effect of govt policies on country situation}
#'   \item{d6hhold}{Financial situation of hhold in 1 yr}
#'   \item{d6cntry}{Economic situation country in 1 yr}
#'   \item{d7hhold}{Effect of govt policies on hhold situation in 1 yr}
#'   \item{d7cntry}{Effect of govt policies on country situation in 1 yr}
#'   \item{d8}{Worry that hhold member unemployed next 12 months}
#'   \item{d9}{How easy to get a job}
#'   \item{d10}{Job availability better in past or future}
#'   \item{d11p1}{Unemployment since 1996 Fed election}
#'   \item{d11p2}{Prices since 1996 Federal election}
#'   \item{d11p3}{Taxes since 1996 Federal election}
#'   \item{d11p4}{Standard of health services since 1996 Fed election}
#'   \item{d11p5}{Crime since 1996 Fed election}
#'   \item{d11p6}{Quality of education since 1996 Fed election}
#'   \item{d11p7}{Quality of indust relations since 1996 Fed election}
#'   \item{d11p8}{Own standard of living since 1996 Fed election}
#'   \item{d11p9}{General standard of living since 1996 Fed election}
#'   \item{d11p10}{Politicians behaviour since 1996 Fed election}
#'   \item{d12}{Government run by big interests}
#'   \item{d13tax}{High tax makes peoples less willing to work}
#'   \item{d13tupow}{Trade unions have too much power}
#'   \item{d13bigpw}{Big business has too much power}
#'   \item{d13socec}{Australia better off with a socialist economy}
#'   \item{d13equal}{Income and wealth should be redistributed}
#'   \item{d13strct}{Stricter laws to regulate trade unions}
#'   \item{d13issu}{Have good understanding of political issues}
#'   \item{d13pjob}{Do as good a job in public office}
#'   \item{d14p1}{Organise public meetings}
#'   \item{d14p2}{Publish pamphlets}
#'   \item{d14p3}{Protest marches and demonstrations}
#'   \item{d14p4}{Occupy Govt office and stop work}
#'   \item{e1}{Choice between taxes and social services}
#'   \item{e2migeo}{Equal opportunities for migrants}
#'   \item{e2nudsex}{Nudity & sex in films and magazines}
#'   \item{e2abland}{Aboriginal land rights}
#'   \item{e2equop}{Equal opportunities for women}
#'   \item{e2immig}{No. of migrants allowed into Australia}
#'   \item{e2abor}{Government help for aborigines}
#'   \item{e2asia}{Building closer links with Asia}
#'   \item{e2arms}{Government controls on firearms}
#'   \item{e3}{Allow euthanasia - patient has incurable disease}
#'   \item{e4}{Allow euthanasia - patient tired of living}
#'   \item{e5}{Feelings about abortion}
#'   \item{e6deathp}{Death penalty reintroduced for murder}
#'   \item{e6marij}{Decriminalise smoking of marijuana}
#'   \item{e6lawbrk}{Stiffer sentences if break law}
#'   \item{e6pref}{Women given preferential treatment}
#'   \item{e6opp}{Increase business opportunities for women}
#'   \item{e7}{In a fair economic system...}
#'   \item{e8}{Competition...}
#'   \item{e9}{Getting ahead in the world is a matter of...}
#'   \item{e10}{People who have made a lot of money...}
#'   \item{e11}{The profit system...}
#'   \item{e12}{Laws for sexual discrimination}
#'   \item{e13}{Jobs be opened to both sexes equally}
#'   \item{e14nengy}{Nuclear energy a necessity}
#'   \item{e14presn}{Nature most precious in life}
#'   \item{e14uran}{Australia should mine its uranium}
#'   \item{e14spend}{Increase spending to protect environment}
#'   \item{e14pollt}{Stronger measures against pollution}
#'   \item{e15envir}{Approve environmental groups}
#'   \item{e15uran}{Approve anti-uranium mining groups}
#'   \item{e15war}{Approve anti-war and anti-nuclear groups}
#'   \item{e16aims1}{Aims of Australia - first choice}
#'   \item{e16aims2}{Aims of Australia - second choice}
#'   \item{e17p1}{Strengthen respect for authority}
#'   \item{e17p2}{EEO in hiring and promotion}
#'   \item{e17p3}{Special effort to protect minorities}
#'   \item{e17p4}{Equality between men and women}
#'   \item{e17p5}{Traditional ideas of right and wrong}
#'   \item{e18}{Ideal Australian society}
#'   \item{e19}{Nature of government}
#'   \item{e20}{Society emphasis on freedom or conformity}
#'   \item{e21}{Aims of society laws}
#'   \item{e22}{Emphasis on institutions or individuals}
#'   \item{f1}{United States alliance under ANZUS}
#'   \item{f2}{Benefits from Australian alliance with US}
#'   \item{f3japan}{Japan threat to Aust security}
#'   \item{f3us}{United States threat to Aust security}
#'   \item{f3china}{China threat to Aust security}
#'   \item{f3png}{Papua New Guinea threat to Aust security}
#'   \item{f3vietn}{Vietnam threat to Aust security}
#'   \item{f3malay}{Malaysia threat to Aust security}
#'   \item{f3singap}{Singapore threat to Aust security}
#'   \item{f3indon}{Indonesia threat to Aust security}
#'   \item{f3nz}{New Zealand threat to Aust security}
#'   \item{f3india}{India threat to Aust security}
#'   \item{f4}{Government spend more on defence}
#'   \item{f5p1}{Aust defence stronger than 10 yrs ago}
#'   \item{f5p2}{Security agreements between Aust and Indon}
#'   \item{f5p3}{Aust would be able to defend itself}
#'   \item{f5p4}{Aust trading future lies with Asia}
#'   \item{f5p5}{Aust use tariffs to protect industry}
#'   \item{f5p6}{Aust should side with Japan not US}
#'   \item{f5p7}{Japan influence too great in Aust}
#'   \item{f5p8}{Limit imports}
#'   \item{f5p9}{Schools teach foreign languages}
#'   \item{f5p10}{Aust follow own interests regardless}
#'   \item{f5p11}{Foreigners shouldn't buy land}
#'   \item{f6}{Number of immigrants increased}
#'   \item{f7p1}{Immigrants increase crime}
#'   \item{f7p2}{Immigrants good for economy}
#'   \item{f7p3}{Immigrants take jobs from Aust born}
#'   \item{f7p4}{Immigrants make Aust more open}
#'   \item{g1}{Importance of Queen}
#'   \item{g2}{Australia a republic}
#'   \item{g3}{Head of republic from voters}
#'   \item{g4}{Change or retain Aust flag}
#'   \item{g5}{Referendum vote on republic}
#'   \item{g6}{Referendum inclination on republic}
#'   \item{g7p1}{All races are equal}
#'   \item{g7p2}{Some breeds of people are better}
#'   \item{g7p3}{Some people are better than others}
#'   \item{g7p4}{Important for children to learn respect for authority}
#'   \item{g8}{Racial prejudice against Asians}
#'   \item{g9}{Racial prejudice against Aborigines}
#'   \item{g10}{Racial prejudice today vs 5 yrs ago}
#'   \item{g11}{Own level of prejudice}
#'   \item{g12asian}{People mind if boss is Asian}
#'   \item{g12abor}{People mind if boss is an Aborigine}
#'   \item{g13asian}{People mind if relative marries Asian}
#'   \item{g13abor}{People mind if relative marries Aborigine}
#'   \item{g14p1}{Changing things makes things worse}
#'   \item{g14p2}{Distrust people who try to be different}
#'   \item{g14p3}{Women should want to have children}
#'   \item{g14p4}{Competition keeps people on their toes}
#'   \item{g14p5}{Migrants should celebrate Aust heritage}
#'   \item{g14p6}{New Austs should try harder to fit in}
#'   \item{g14p7}{Special cultural protection for Aborigines}
#'   \item{g14p8}{Recognise aspirations of Aborigines}
#'   \item{g14p9}{Aborigines right to self-government}
#'   \item{g15}{Homosexuals teach in schools}
#'   \item{g16}{Homosexuals hold positions of power}
#'   \item{g17p1}{Important to self image: job}
#'   \item{g17p2}{Important to self image:  town}
#'   \item{g17p3}{Important to self image: social class}
#'   \item{g17p4}{Important to self image: being Australian}
#'   \item{g17p5}{Important to self image: political party}
#'   \item{g17p6}{Important to self image: state}
#'   \item{g17p7}{Important to self image: ethnicity/race}
#'   \item{g17p8}{Important to self image: religion}
#'   \item{g17p9}{Important to self image: gender}
#'   \item{g17p10}{Important to self image: sports team}
#'   \item{g17p11}{Important to self image: ideas seen as equal}
#'   \item{g17p12}{Important to self image: your freedom}
#'   \item{g17p13}{Important to self image: feeling good}
#'   \item{g17p14}{Important to self image: looking good}
#'   \item{h1}{Age left school}
#'   \item{h2}{No. years tertiary education}
#'   \item{h3}{Highest qual obtained since leaving school}
#'   \item{h4}{Occupation last week}
#'   \item{h5occ}{Occupation}
#'   \item{h5pos}{Position in organisation}
#'   \item{h5employ}{Employer}
#'   \item{h5superv}{Supervisory responsibility}
#'   \item{h6}{Belong to a trade union}
#'   \item{i1}{Sex}
#'   \item{i2}{Year of birth}
#'   \item{i3own}{Country of birth}
#'   \item{i3mum}{Mothers country of birth}
#'   \item{i3dad}{Fathers country of birth}
#'   \item{i4dad}{Fathers party ID at 14}
#'   \item{i4mum}{Mothers party ID at 14}
#'   \item{i5}{Religion}
#'   \item{i6}{Religious attendance}
#'   \item{i7}{Marital status}
#'   \item{i8}{Own, buying or rent home}
#'   \item{i9}{Own a personal computer}
#'   \item{i10}{Own a motor cycle}
#'   \item{i11}{Own a firearm}
#'   \item{i12}{Social class}
#'   \item{i13}{Live rural or urban}
#'   \item{i14}{Gross annual income}
#'   \item{i15}{Spouse working}
#'   \item{i16occ}{Spouse occupation}
#'   \item{i17}{Spouse employer}
#'   \item{i18}{Does spouse supervise people at work}
#'   \item{i19}{Spouse member of trade union}
#'   \item{i20}{Spouse party identification}
#'   \item{date}{Date of Return}
#'   \item{state}{State}
#'   \item{elecdiv}{Electoral division}
#'   \item{region}{Region}
#'   \item{xh5occ}{EXTENDED:Occupation}
#'   \item{xi16occ}{EXTENDED:Spouse occupation}
#'   \item{xi3own}{EXTENDED:Country of birth}
#'   \item{xi3mum}{EXTENDED:Mothers country of birth}
#'   \item{xi3dad}{EXTENDED:Fathers country of birth}
#'   \item{xi5}{EXTENDED:Religion}
#'   \item{statemap}{State mapping variable}
#' }
"aes_1998"
