#' Australian Election Study 2004
#'
#' \itemize{
#'    \item Total sample: 4,250
#'    \item Valid responses: 1,769
#'    \item Effective response rate: 44.5
#' }
#'
#' @details
#'
#' The 2004 Australian Election Study is the seventh in a series of surveys beginning in 1987 that
#' have been timed to coincide with Australian Federal elections. The series also builds on the
#' 1967, 1969 and 1979 Australian Political Attitudes Surveys. The Australian Election Studies aim
#' to provide a long-term perspective on stability and change in the political attitudes and
#' behaviour of the Australian electorate, and investigate the changing social bases of Australian
#' politics as the economy and society modernise and change character. In addition to these
#' long-term goals they examine the political issues prevalent in the election and assess their
#' importance for the election result.
#'
#' The 2004 survey replicates many questions from the previous Australian Election Studies, but also
#' introduces a variety of new questions including a section on political and global issues. Other
#' sections cover the respondent's interest in the election campaign and politics, their past and
#' present political affiliation, evaluation of parties and candidates, alignment with parties on
#' various election issues, evaluation of the current economic situation, attitudes to a range of
#' election issues including the immigration, refugees and asylum seekers, terrorism, taxation,
#' unemployment, and interest rates, attitudes to issues relating to the environment and defence,
#' and opinions on various social policy issues including abortion, equal opportunities, sex
#' discrimination, and government assistance to Aborigines.
#'
#' Background variables include level of education, employment status, occupation, type of employer,
#' position at workplace, trade union membership, sex, age, own and parents' country of birth,
#' parents' political preferences, religion, marital status, income, and where applicable, the
#' occupation, trade union membership and political preference of the respondent's spouse.
#'
#' \strong{Useful Links}
#' \itemize{
#'    \item \href{http://ada.edu.au/ADAData/codebooks/ADA.CODEBOOK.01079.pdf.zip}{Original codebook}
#'    \item \href{http://ada.edu.au/ADAData/questionnaires/ADA.QUESTIONNAIRE.01079.pdf.zip}{Original questionnaire}
#' }
#'
#' @source \url{http://www.australianelectionstudy.org/voter_studies.html}
#'
#' @section Variables:
#'
#' Note: this documentation has been autogenerated from the dataset labels not the original codebook.
#'
#' \describe{
#'   \item{acc}{Accession number}
#'   \item{retda}{Day of return}
#'   \item{retmo}{Month of return}
#'   \item{retyr}{Year of return}
#'   \item{a1}{A1. Interest in politics}
#'   \item{a2}{A2. Followed election news in the newspapers}
#'   \item{a3p1}{A3. Followed election news on TV}
#'   \item{a3p2}{A3. Followed election news on the radio}
#'   \item{a4}{A4. Interest in election campaign}
#'   \item{a5p1}{A5. During election: discussed politics with others}
#'   \item{a5p2}{A5. During election: talk to people about vote}
#'   \item{a5p3}{A5. During election: work for party/candidate}
#'   \item{a5p4}{A5. During election: go to meetings or rallies}
#'   \item{a5p5}{A5. During campaign: contribute money}
#'   \item{a6}{A6. Candidate persuade you to vote for them}
#'   \item{a7}{A7. Watched televised debate 12 September}
#'   \item{a8}{A8. Who performed better in televised debate}
#'   \item{a9}{A9. Listen to political talkback radio}
#'   \item{a10}{A10. Use internet to get news about 2004 Fed election}
#'   \item{a11p1}{A11. Website: Party}
#'   \item{a11p2}{A11. Website: Own MP}
#'   \item{a11p3}{A11. Website: Individual candidate in your electorate}
#'   \item{a11p4}{A11. Website: Other candidate/MP outside your electorate}
#'   \item{a11p5}{A11. Website: Federal parliament}
#'   \item{a11p6}{A11. Website: Australian Electoral Commission}
#'   \item{a11p7}{A11. Website: Fun/political humour}
#'   \item{a11p8}{A11. Website: Online opinion poll}
#'   \item{a11p9}{A11. Website: Mainstream news media}
#'   \item{a11p10}{A11. Website: Political weblog/blog}
#'   \item{a12}{A12. Should voting be compulsory}
#'   \item{a13}{A13. Would you vote if voting not compulsory}
#'   \item{b1}{B1. Party identification}
#'   \item{xb1}{B1. Extended-Party identification}
#'   \item{b2}{B2. Strength of party identification}
#'   \item{b3}{B3. Care which party wins election}
#'   \item{b4}{B4. When decided which way to vote}
#'   \item{b5}{B5. Most important in vote decision}
#'   \item{b6}{B6. Prefer when Govt controls both houses}
#'   \item{b7}{B7. Difference between Labor and Liberal}
#'   \item{b8}{B8. Parties doing good or bad job}
#'   \item{b9}{B9. Parties observe standards managing internal affairs}
#'   \item{b10own}{B10. Own left-right position}
#'   \item{b10lib}{B10. Liberal left-right position}
#'   \item{b10alp}{B10. Labor left-right position}
#'   \item{b10nat}{B10. Nationals left-right position}
#'   \item{b10dem}{B10. Democrats left-right position}
#'   \item{b10onp}{B10. One Nation Party left-right position}
#'   \item{b10grn}{B10. Greens left-right position}
#'   \item{b11reps}{B11. Vote in House of Representatives}
#'   \item{xb11reps}{B11. Extended-Vote in House of Representatives}
#'   \item{b11senat}{B11. Vote in Senate}
#'   \item{xb11sena}{B11. Extended-Vote in Senate}
#'   \item{b12reps}{B12. Preferences to in House of Reps}
#'   \item{b12senat}{B12. Preferences to in Senate}
#'   \item{b13}{B13. Followed How to Vote card for H of R}
#'   \item{b14}{B14. Party box or own preferences for Senate}
#'   \item{b15}{B15. Thought of changing vote during campaign}
#'   \item{b16}{B16. Vote in House of Representatives in 2001}
#'   \item{b17}{B17. Party voted for perform last 3 years}
#'   \item{b18p1}{B18. Previous vote - always same}
#'   \item{b18p2}{B18. Previous vote - sometimes Liberal}
#'   \item{b18p3}{B18. Previous vote - sometimes Labor}
#'   \item{b18p4}{B18. Previous vote - sometimes National}
#'   \item{b18p5}{B18. Previous vote - sometimes Democrats}
#'   \item{b18p6}{B18. Previous vote - sometimes others}
#'   \item{b18p7}{B18. Previous vote - not before this election}
#'   \item{b19}{B19. Previous State election vote}
#'   \item{b20}{B20. Elections ensure all voters represented}
#'   \item{b21}{B21. Party represents your views best}
#'   \item{b22}{B22. Party leader represents your views best}
#'   \item{b23}{B23. Political parties care what people think}
#'   \item{b24}{B24. Political parties make system work}
#'   \item{b25lib}{B25. Feelings about Liberal Party}
#'   \item{b25alp}{B25. Feelings about Labor Party}
#'   \item{b25nat}{B25. Feelings about National Party}
#'   \item{b25grn}{B25. Feelings about Greens}
#'   \item{b25onp}{B25. Feelings about One Nation Party}
#'   \item{b25dem}{B25. Feelings about Australian Democrats}
#'   \item{c1lath}{C1. Feelings about Mark Latham}
#'   \item{c1how}{C1. Feelings about John Howard}
#'   \item{c1and}{C1. Feelings about John Anderson}
#'   \item{c1bart}{C1. Feelings about Andrew Bartlett}
#'   \item{c1hans}{C1. Feelings about Pauline Hanson}
#'   \item{c1brown}{C1. Feelings about Bob Brown}
#'   \item{c1cost}{C1. Feelings about Peter Costello}
#'   \item{c1crean}{C1. Feelings about Simon Crean}
#'   \item{c1bush}{C1. Feelings about George W Bush}
#'   \item{c1blair}{C1. Feelings about Tony Blair}
#'   \item{c2jhint}{C2. John Howard intelligent}
#'   \item{c2jhcom}{C2. John Howard compassionate}
#'   \item{c2jhsen}{C2. John Howard sensible}
#'   \item{c2jhlea}{C2. John Howard provides strong leadership}
#'   \item{c2jhhon}{C2. John Howard honest}
#'   \item{c2jhkno}{C2. John Howard knowledgeable}
#'   \item{c2jhins}{C2. John Howard inspiring}
#'   \item{c2jhtru}{C2. John Howard trustworthy}
#'   \item{c3mlint}{C3. Mark Latham intelligent}
#'   \item{c3mlcom}{C3. Mark Latham compassionate}
#'   \item{c3mlsen}{C3. Mark Latham sensible}
#'   \item{c3mllea}{C3. Mark Latham provides strong leadership}
#'   \item{c3mlhon}{C3. Mark Latham honest}
#'   \item{c3mlkno}{C3. Mark Latham knowledgeable}
#'   \item{c3mlins}{C3. Mark Latham inspiring}
#'   \item{c3mltru}{C3. Mark Latham trustworthy}
#'   \item{c4}{C4. Fed Politicians know what people think}
#'   \item{c5}{C5. Doesn't make a difference who in power}
#'   \item{c6}{C6. Doesn't make a difference who vote for}
#'   \item{c7}{C7. Satisfied with Aust democracy}
#'   \item{c8}{C8. Government looks after themselves}
#'   \item{c9}{C9. Government run by big interests}
#'   \item{c10}{C10. Performance of govt in Canb 3 yrs}
#'   \item{c11}{C11. Democracy better than other govt}
#'   \item{c12}{C12. Cost of fine if don't vote}
#'   \item{c13}{C13. Proportion who pay fine}
#'   \item{c14p1}{C14. Makes sense to vote for small parties}
#'   \item{c14p2}{C14. Bans on companies donating money}
#'   \item{c14p3}{C14. Politicians commonly rort the system}
#'   \item{c14p4}{C14. Have good understanding of political issues}
#'   \item{c14p5}{C14. Do as good a job in public office as most others}
#'   \item{c14p6}{C14. Doesn't care about election shouldn't vote}
#'   \item{c14p7}{C14. If I did not vote I would feel guilty}
#'   \item{c15p1}{C15. Strong leader who doesn't bother with parliament}
#'   \item{c15p2}{C15. Experts, not government, make decisions}
#'   \item{c15p3}{C15. Having the army rule}
#'   \item{c15p4}{C15. Having a democratic political system}
#'   \item{c16}{C16. Corruption amongst politicians}
#'   \item{c17}{C17. Corruption amongst public servants}
#'   \item{c18p1}{C18. 5 yrs done to express views-contact official}
#'   \item{c18p2}{C18. 5 yrs done to express views-protest/march}
#'   \item{c18p3}{C18. 5 yrs done to express views-work with like others}
#'   \item{c18p4}{C18. 5 yrs done to express views-signed written petition}
#'   \item{c18p5}{C18. 5 yrs done to express views-signed electronic petition}
#'   \item{d1tax}{D1. Importance of taxation}
#'   \item{d1immig}{D1. Importance of immigration}
#'   \item{d1educ}{D1. Importance of education}
#'   \item{d1envir}{D1. Importance of environment}
#'   \item{d1indrel}{D1. Importance of industrial relations}
#'   \item{d1health}{D1. Importance of health and Medicare}
#'   \item{d1refuge}{D1. Importance of refugees, asylum seekers}
#'   \item{d1defenc}{D1. Importance of defence, national security}
#'   \item{d1iraq}{D1. Importance of the war in Iraq}
#'   \item{d1unemp}{D1. Importance of unemployment}
#'   \item{d1inter}{D1. Importance of interest rates}
#'   \item{d1terror}{D1. Importance of terrorism}
#'   \item{d2tax}{D2. Party closest to own view taxation}
#'   \item{d2immig}{D2. Party closest to own view immigration}
#'   \item{d2educ}{D2. Party closest to own view education}
#'   \item{d2envir}{D2. Party closest to own view environment}
#'   \item{d2indrel}{D2. Party closest to own view industrial relations}
#'   \item{d2health}{D2. Party closest to own view health and Medicare}
#'   \item{d2refuge}{D2. Party closest to own view refugees, asylum seekers}
#'   \item{d2defenc}{D2. Party closest to own view defence, national security}
#'   \item{d2iraq}{D2. Party closest to own view war in Iraq}
#'   \item{d2unemp}{D2. Party closest to own view unemployment}
#'   \item{d2inter}{D2. Party closest to own view interest rates}
#'   \item{d2terror}{D2. Party closest to own view terrorism}
#'   \item{d3p1}{D3. Most important issue during election campaign}
#'   \item{d3p2}{D3. Second important issue during election campaign}
#'   \item{d4}{D4. Most important issue-govt do a good job 3 yrs}
#'   \item{d5hhold}{D5. Financial situation of hhold now to 1 yr ago}
#'   \item{d5cntry}{D5. Economic situation country now to 1 yr ago}
#'   \item{d6hhold}{D6. Effect of govt policies on hhold situation}
#'   \item{d6cntry}{D6. Effect of govt policies on country situation}
#'   \item{d7hhold}{D7. Financial situation of hhold in 1 yr}
#'   \item{d7cntry}{D7. Economic situation country in 1 yr}
#'   \item{d8hhold}{D8. Effect of govt policies on hhold situation in 1 yr}
#'   \item{d8cntry}{D8. Effect of govt policies on country situation in 1 yr}
#'   \item{d9}{D9. Worry that hhold member will unemployed next 12 months}
#'   \item{d10}{D10. How easy to get a job}
#'   \item{d11}{D11. Job availability better in past or future}
#'   \item{d12}{D12. How worried about increases in interest rates}
#'   \item{d13}{D13. Opinion on cutting income tax}
#'   \item{d14p1}{D14. Unemployment since 2001 Fed election}
#'   \item{d14p2}{D14. Prices since 2001 Federal election}
#'   \item{d14p3}{D14. Taxes since 2001 Federal election}
#'   \item{d14p4}{D14. Standard of health services since 2001 Fed election}
#'   \item{d14p5}{D14. Quality of education since 2001 Fed election}
#'   \item{d14p6}{D14. Quality of indust rels since 2001 Fed election}
#'   \item{d14p7}{D14. Own standard of living since 2001 Fed election}
#'   \item{d14p8}{D14. General standard of living since 2001 Fed election}
#'   \item{d15p1}{D15. High tax makes people less willing to work}
#'   \item{d15p2}{D15. Trade unions have too much power}
#'   \item{d15p3}{D15. Big business has too much power}
#'   \item{d15p4}{D15. Income and wealth should be redistributed}
#'   \item{d15p5}{D15. Private schools offer better education than public}
#'   \item{d15p6}{D15. Stricter laws to regulate trade unions}
#'   \item{e1}{E1. Choice between taxes and social services}
#'   \item{e2migeo}{E2. Equal opportunities for migrants}
#'   \item{e2nudsex}{E2. Nudity & sex in films and magazines}
#'   \item{e2abland}{E2. Aboriginal land rights}
#'   \item{e2equop}{E2. Equal opportunities for women}
#'   \item{e2immig}{E2. No. of migrants allowed into Australia}
#'   \item{e2disab}{E2. Equal opportunities for people with disabilities}
#'   \item{e2abor}{E2. Government help for aborigines}
#'   \item{e2asia}{E2. Building closer relations with Asia}
#'   \item{e2arms}{E2. Government controls on firearms}
#'   \item{e2terror}{E2. Aust support fight against terrorism}
#'   \item{e3}{E3. Feelings about abortion}
#'   \item{e4deathp}{E4. Death penalty reintroduced for murder}
#'   \item{e4marij}{E4. Decriminalise smoking of marijuana}
#'   \item{e4lawbrk}{E4. Stiffer sentences if break law}
#'   \item{e4asylum}{E4. Asylum seekers turned back}
#'   \item{e4pollut}{E4. Stronger measures against pollution}
#'   \item{e4school}{E4. Public schools don't receive fair share of budget}
#'   \item{e4pref}{E4. Women given preferential treatment}
#'   \item{e4opp}{E4. Increase business opportunities for women}
#'   \item{e5p1}{E5. Env concern - pollution}
#'   \item{e5p2}{E5. Env concern - waste disposal}
#'   \item{e5p3}{E5. Env concern - logging of forests}
#'   \item{e5p4}{E5. Env concern - destruction wildlife}
#'   \item{e5p5}{E5. Env concern - soil degradation}
#'   \item{e5p6}{E5. Env concern - greenhouse effect}
#'   \item{e5p7}{E5. Env concern - genetically modified crops}
#'   \item{e5p8}{E5. Env concern - cloning human tissue}
#'   \item{e6}{E6. How likely to join environmental group}
#'   \item{e7p1}{E7. Aims 10yrs 1-First choice}
#'   \item{e7p2}{E7. Aims 10yrs 1-Second choice}
#'   \item{e8p1}{E8. Aims 10yrs 2-First choice}
#'   \item{e8p2}{E8. Aims 10yrs 2-Second choice}
#'   \item{e9p1}{E9. Aims 10yrs 3-First choice}
#'   \item{e9p2}{E9. Aims 10yrs 3-Second choice}
#'   \item{f1}{F1. United States alliance under ANZUS}
#'   \item{f2}{F2. If Australia threatened, trust US to defend}
#'   \item{f3japan}{F3. Japan threat to Aust. security}
#'   \item{f3us}{F3. United States threat to Aust. security}
#'   \item{f3china}{F3. China threat to Aust. security}
#'   \item{f3png}{F3. Papua New Guinea threat to Aust. security}
#'   \item{f3vietn}{F3. Vietnam threat to Aust. security}
#'   \item{f3malay}{F3. Malaysia threat to Aust. security}
#'   \item{f3singap}{F3. Singapore threat to Aust. security}
#'   \item{f3indon}{F3. Indonesia threat to Aust. security}
#'   \item{f3nz}{F3. New Zealand threat to Aust. security}
#'   \item{f3india}{F3. India threat to Aust. security}
#'   \item{f4}{F4. Government spend more on defence}
#'   \item{f5p1}{F5. Aust defence stronger than 10 yrs ago}
#'   \item{f5p2}{F5. Security agreements between Aust and Indon}
#'   \item{f5p3}{F5. Aust would be able to defend itself}
#'   \item{f5p4}{F5. Aust trading future lies with Asia}
#'   \item{f5p5}{F5. Aust provide military for war on terrorism}
#'   \item{f6}{F6. Approve of way Howard handled war in Iraq}
#'   \item{f7}{F7. War in Iraq been worth the cost}
#'   \item{f8}{F8. Threat of terrorism against Australia increased}
#'   \item{f9}{F9. Number of immigrants increased}
#'   \item{f10p1}{F10. Immigrants increase crime}
#'   \item{f10p2}{F10. Immigrants good for economy}
#'   \item{f10p3}{F10. Immigrants take jobs from Aust}
#'   \item{f10p4}{F10. Immigrants make Aust more open}
#'   \item{g1}{G1. Respect for individual freedom}
#'   \item{g2}{G2. Most people can be trusted}
#'   \item{g3}{G3. Importance of Queen}
#'   \item{g4}{G4. Australia a republic}
#'   \item{g5}{G5. Head of republic from voters}
#'   \item{g6p1}{G6. Rather be a citizen of Australia}
#'   \item{g6p2}{G6. Change things makes worse}
#'   \item{g6p3}{G6. Distrust people try to be different}
#'   \item{g6p4}{G6. People come here should be more like Australians}
#'   \item{g6p5}{G6. Citizen of the world as well as Australia}
#'   \item{g6p6}{G6. Up to each country to deal with environment}
#'   \item{g6p7}{G6. People seeking asylum are political refugees}
#'   \item{g6p8}{G6. Important new migrants learn to be Australian}
#'   \item{g6p9}{G6. Obedience and respect for authority important}
#'   \item{g6p10}{G6. Person with bad manners not get along with people}
#'   \item{g6p11}{G6. People in two groups: weak and strong}
#'   \item{g6p12}{G6. Nothing lower than person doesn't respect parents}
#'   \item{g6p13}{G6. Insult to honour should always be punished}
#'   \item{g6p14}{G6. Young people need strict discipline}
#'   \item{g7}{G7. Emotionally attached to Australia}
#'   \item{g8}{G8. How proud to be Australian}
#'   \item{g9}{G9. Globalisation: overall}
#'   \item{g10p1}{G10. Globalisation: providing jobs in poor countries}
#'   \item{g10p2}{G10. Globalisation: democracy and human rights}
#'   \item{g10p3}{G10. Globalisation: consumers like you}
#'   \item{g10p4}{G10. Globalisation: Australian companies}
#'   \item{g10p5}{G10. Globalisation: cultural diversity}
#'   \item{g10p6}{G10. Globalisation: Australian economy}
#'   \item{g10p7}{G10. Globalisation: own standard of living}
#'   \item{g10p8}{G10. Globalisation: creating jobs in Aust}
#'   \item{g10p9}{G10. Globalisation: the environment}
#'   \item{g10p10}{G10. Globalisation: job security}
#'   \item{g10p11}{G10. Globalisation: Australian culture}
#'   \item{g10p12}{G10. Globalisation: range of choice}
#'   \item{g10p13}{G10. Globalisation: sample different cultures}
#'   \item{g10p14}{G10. Globalisation: learn about other cultures}
#'   \item{g10p15}{G10. Globalisation: access goods and services}
#'   \item{g11}{G11. Role of international institutions}
#'   \item{g12}{G12. Travelled outside Australia}
#'   \item{g13}{G13. Primary source of news}
#'   \item{g14}{G14. Own shares in Australian Stock Exchange}
#'   \item{g15}{G15. Year first acquired shares}
#'   \item{g16}{G16. Own shares in company you work for}
#'   \item{g17}{G17. Own 'new technology' shares}
#'   \item{g18}{G18. Federal Treasurer before 2004 election}
#'   \item{g19}{G19. Party with second largest number of seats}
#'   \item{g20}{G20. Proportion tax paid on low income}
#'   \item{g21chi}{G21. UN Security Council: China}
#'   \item{g21rus}{G21. UN Security Council: Russia}
#'   \item{g21fra}{G21. UN Security Council: France}
#'   \item{g21uk}{G21. UN Security Council: UK}
#'   \item{g21us}{G21. UN Security Council: US}
#'   \item{g21dk}{G21. UN Security Council: Don't know}
#'   \item{g21cor}{G21. UN Security Council: Correct answer}
#'   \item{g21inc}{G21. UN Security Council: Incorrect answer}
#'   \item{g22}{G22. Who is entitled to vote in elections (HofR)}
#'   \item{g23}{G23. Maximum years allowed between elections (HofR)}
#'   \item{g24}{G24. Who was 'Pig-iron Bob'}
#'   \item{g25}{G25. Political party formed by former Liberal minister}
#'   \item{g26}{G26. Most recent Australian Labor Party Prime Minister}
#'   \item{h1}{H1. Age left school}
#'   \item{h2}{H2. No. years tertiary education}
#'   \item{h3}{H3. Highest qualification since leaving school}
#'   \item{h4}{H4. Occupation last week}
#'   \item{h5you}{H5. Secondary school attended - You}
#'   \item{h5child}{H5. Secondary school attended - Child}
#'   \item{h6occ}{H6. Occupation}
#'   \item{xh6occ}{H6. Occupation - ASCO2}
#'   \item{h6pos}{H6. Position in organisation}
#'   \item{h6employ}{H6. Employer}
#'   \item{h6superv}{H6. Supervisory responsibility}
#'   \item{h7}{H7. Belong to a trade union}
#'   \item{i1}{I1. Sex}
#'   \item{i2}{I2. Year of birth}
#'   \item{i3own}{I3. Country of birth}
#'   \item{xi3own}{I3. Extended-Country of birth}
#'   \item{i3mum}{I3. Mothers country of birth}
#'   \item{xi3mum}{I3. Extended-Mothers country of birth}
#'   \item{i3dad}{I3. Fathers country of birth}
#'   \item{xi3dad}{I3. Extended-Fathers country of birth}
#'   \item{i4}{I4. Year came to Australia}
#'   \item{i5dad}{I5. Fathers party ID at 14}
#'   \item{i5mum}{I5. Mothers party ID at 14}
#'   \item{i6}{I6. Religion}
#'   \item{xi6}{I6. Extended-Religion}
#'   \item{i7}{I7. Religious attendance}
#'   \item{i8}{I8. Marital status}
#'   \item{i9}{I9. Own, buying or rent home}
#'   \item{i10}{I10. Own a firearm}
#'   \item{i11}{I11. Own a personal computer}
#'   \item{i12}{I12. How often use internet}
#'   \item{i13}{I13. When start using internet}
#'   \item{i14}{I14. You get cable or satellite television}
#'   \item{i15p1}{I15. Member: Business or employers' association}
#'   \item{i15p2}{I15. Member: Farmers' association}
#'   \item{i15p3}{I15. Member: Professional organisation}
#'   \item{i15p4}{I15. Member: Charitable organisation}
#'   \item{i15p5}{I15. Member: Sport/recreation organisation}
#'   \item{i16}{I16. Social class}
#'   \item{i17}{I17. Live rural or urban}
#'   \item{i18}{I18. Gross annual income}
#'   \item{i19}{I19. Spouse working now}
#'   \item{i20}{I20. Spouse occupation}
#'   \item{xi20}{I20. Spouse occupation - ASCO2}
#'   \item{i21}{I21. Spouse employer}
#'   \item{i22}{I22. Does spouse supervise people at work}
#'   \item{i23}{I23. Spouse member of trade union}
#'   \item{i24}{I24. Spouse party identification}
#'   \item{xi24}{I24. Extended-Spouse party identification}
#'   \item{state}{State}
#'   \item{elecdiv}{Electoral Division}
#'   \item{pcode}{RESTRICTED VARIABLE: Postcode}
#'   \item{region}{Region}
#'   \item{subsam}{Subsample}
#'   \item{statemap}{State mapping variable}
#' }
"aes_2004"
